DROP  DATABASE IF EXISTS `TechShop`;
CREATE DATABASE `TechShop` CHARACTER SET utf8;

USE `TechShop`;

CREATE TABLE `Role`
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(80) UNIQUE,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Account` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Email` VARCHAR(80) UNIQUE,
	`Password` VARCHAR(2048),
	`Fullname` VARCHAR(80),
	`RoleID` INT NOT NULL,
	`Status` INT NOT NULL,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`RoleID`) REFERENCES `Role`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `OAuthAccessToken` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`AccessToken` VARCHAR(1024) UNIQUE,
	`Expires` INT,
	`ExpiredAt` DATETIME NOT NULL,
	`AccountID` INT NOT NULL,
	`Status` INT NOT NULL,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`AccountID`) REFERENCES `Account`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Category` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(200) UNIQUE,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Item` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(200) NOT NULL,
	`Price` FLOAT,
	`Amount` INT NOT NULL,
	`CategoryID` INT NOT NULL,
	`ImageURLs` VARCHAR(10240),
	`Description` VARCHAR(5000),
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Item_Has_Category`
(
  `ID` int NOT NULL AUTO_INCREMENT,
  `CategoryID` int,
  `ItemID` int,
  `CreatedAt` datetime,
  `UpdatedAt` datetime,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`CategoryID`) REFERENCES `Category`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Comment` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`ItemID` INT NOT NULL,
	`AccountID` INT NOT NULL,
	`Content` VARCHAR(500),
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`ItemID`) REFERENCES `Item`(`ID`),
	FOREIGN KEY (`AccountID`) REFERENCES `Account`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `OrderAddress` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Fullname` VARCHAR(200) NOT NULL,
	`Phone` VARCHAR(15) NOT NULL,
	`Address` VARCHAR(200) NOT NULL,
	`City` VARCHAR(200),
	`Province` VARCHAR(200),
	`District` VARCHAR(200),
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Order` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`OrderAddressID` INT NOT NULL,
	`AccountID` INT NOT NULL,
	`Status` INT NOT NULL,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`OrderAddressID`) REFERENCES `OrderAddress`(`ID`),
	FOREIGN KEY (`AccountID`) REFERENCES `Account`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Order_Has_Item` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`OrderID` INT NOT NULL,
	`ItemID` INT NOT NULL,
	`DiscountPriceID` INT NOT NULL,
	`StartingTime` DATETIME NOT NULL,
	`EndingTime` DATETIME NOT NULL,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`OrderID`) REFERENCES `Order`(`ID`),
	FOREIGN KEY (`ItemID`) REFERENCES `Item`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `DiscountPrice` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`ItemID` INT,
	`DiscountPrice` INT NOT NULL,
	`Percent` INT NOT NULL,
	`StartingDay` datetime,
	`EndingDay` datetime,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`ItemID`) REFERENCES `Item`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO Role(Name) VALUES("admin"), ("normal_user");