DROP  DATABASE IF EXISTS `TechShop`;
CREATE DATABASE `TechShop` CHARACTER SET utf8;

USE `TechShop`;

CREATE TABLE `Role`
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(80) UNIQUE,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Account` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Email` VARCHAR(80) UNIQUE,
	`Password` VARCHAR(2048),
	`Fullname` VARCHAR(80),
	`RoleID` INT NOT NULL,
	`Status` INT NOT NULL,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`RoleID`) REFERENCES `Role`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `OAuthAccessToken` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`AccessToken` VARCHAR(1024) UNIQUE,
	`Expires` INT,
	`ExpiredAt` DATETIME NOT NULL,
	`AccountID` INT NOT NULL,
	`Status` INT NOT NULL,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`AccountID`) REFERENCES `Account`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Category` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(200) UNIQUE,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Item` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(1000) NOT NULL,
	`Price` INT,
	`Amount` INT NOT NULL,
	`Warranty` VARCHAR(200),
	`ImageURLs` TEXT,
	`Infos` TEXT,
	`Technical_Infos` TEXT,
	`Description` VARCHAR(5000),
	`CategoryID` INT NOT NULL,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`CategoryID`) REFERENCES `Category`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Rating`
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Value` INT NOT NULL,
	`ItemID` INT NOT NULL,
	`AccountID` INT NOT NULL,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`ItemID`) REFERENCES `Item`(`ID`),
	FOREIGN KEY (`AccountID`) REFERENCES `Account`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Item_Has_Category`
(
	`ID` int NOT NULL AUTO_INCREMENT,
	`CategoryID` int,
	`ItemID` int,
	`CreatedAt` datetime,
	`UpdatedAt` datetime,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`CategoryID`) REFERENCES `Category`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Comment` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`ItemID` INT NOT NULL,
	`AccountID` INT NOT NULL,
	`Content` VARCHAR(500),
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`ItemID`) REFERENCES `Item`(`ID`),
	FOREIGN KEY (`AccountID`) REFERENCES `Account`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `OrderAddress` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Fullname` VARCHAR(200) NOT NULL,
	`Phone` VARCHAR(15) NOT NULL,
	`Address` VARCHAR(200) NOT NULL,
	`City` VARCHAR(200),
	`Province` VARCHAR(200),
	`District` VARCHAR(200),
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Order` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`OrderAddressID` INT NOT NULL,
	`AccountID` INT NOT NULL,
	`Status` INT NOT NULL,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`OrderAddressID`) REFERENCES `OrderAddress`(`ID`),
	FOREIGN KEY (`AccountID`) REFERENCES `Account`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Order_Has_Item` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`OrderID` INT NOT NULL,
	`ItemID` INT NOT NULL,
	`DiscountPriceID` INT NOT NULL,
	`StartingTime` DATETIME NOT NULL,
	`EndingTime` DATETIME NOT NULL,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`OrderID`) REFERENCES `Order`(`ID`),
	FOREIGN KEY (`ItemID`) REFERENCES `Item`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `DiscountPrice` 
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`ItemID` INT,
	`DiscountPrice` INT NOT NULL,
	`Percent` INT NOT NULL,
	`StartingDay` datetime,
	`EndingDay` datetime,
	`CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`ItemID`) REFERENCES `Item`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Category

INSERT INTO Category (Name) VALUES ('Máy tính xách tay');
INSERT INTO Category (Name) VALUES ('Máy tính bộ all in one');
INSERT INTO Category (Name) VALUES ('Điện thoại - table - đồ chơi');
INSERT INTO Category (Name) VALUES ('Linh kiện máy tính');
INSERT INTO Category (Name) VALUES ('Phụ kiện - gaming gear');
INSERT INTO Category (Name) VALUES ('Thiết bị mạng - wifi');
INSERT INTO Category (Name) VALUES ('Thiết bị văn phòng');
INSERT INTO Category (Name) VALUES ('camera - an ninh - giải pháp');
INSERT INTO Category (Name) VALUES ('Thiết bị siêu thị - gia đình');
INSERT INTO Category (Name) VALUES ('Âm thanh - chiếu sáng');
INSERT INTO Category (Name) VALUES ('Apple center');

-- Role
INSERT INTO Role (Name) VALUES ('ROLE_ADMIN'),
('ROLE_NORMAL_USER');

